---
- name: Instalando WordPress
  hosts: all
  remote_user: ec2-user
  become: yes
  vars_files:
    - vars/vars.yaml
  tasks:
    - name: Instalando pacotes necessários para WordPress
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - php8.2
        - php8.2-fpm
        - mariadb105-server
        - php-mysqlnd
        - python3-pip

    - name: Iniciando e habilitando serviços
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - php-fpm
        - mariadb

    - name: Instalando pexpect
      pip:
        name: pexpect
        state: present
 
 

    - name: Criando arquivo de configuração do Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/blog-gilberto-lira.dreamsquad.com.br.conf
      
       
    - name: Checando se o diretório já existe
      stat:
        path: "{{ dir_wordpress }}"
      register: wordpress_dir
    
    - name: Criando diretório do WordPress
      file:
        path: "{{ dir_wordpress }}"
        state: directory
      when: not wordpress_dir.stat.exists
      

    - name: Baixando WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Descompactando WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/
        remote_src: yes
      when: not wordpress_dir.stat.exists    

    - name: Copiando arquivo de configuração do WordPress
      copy:
        src: "{{ dir_wordpress }}/wp-config-sample.php"
        dest: "{{ dir_wordpress }}/wp-config.php"
        remote_src: yes
      when: not wordpress_dir.stat.exists or wordpress_dir.stat.islnk    

    - name: Substituindo as variaveis do arquivo de configuração do WordPress
      replace:
        path: "{{ dir_wordpress }}/wp-config.php"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - regexp: "'DB_NAME', '.*'"
          replace: "'DB_NAME', 'wordpress'"
        - regexp: "'DB_USER', '.*'"
          replace: "'DB_USER', 'wp_user'"
        - regexp: "'DB_PASSWORD', '.*'"
          replace: "'DB_PASSWORD', '{{ bd_senha }}'"

    
    
    
    - name: Iniciando configuração do MySQL
      expect:
        command: sudo mysql_secure_installation
        responses:
          "Enter current password for root (enter for none):": "{{ bd_senha }}"
          "Switch to unix_socket authentication [Y/n]": "y"
          "Change the root password?[Y/n]": "n"
          "Remove anonymous users? [Y/n]": "y"
          "Disallow root login remotely? [Y/n]": "y"
          "Remove test database and access to it? [Y/n]": "y"
          "Reload privilege tables now? [Y/n]": "y"
        timeout: 1
      register: secure_mariadb
      changed_when: secure_mariadb.stdout.find('... Already locked.') == -1
      failed_when: "'... Failed!' in secure_mariadb.stdout_lines"

    - name: Criando database para o WordPress
      command: >
        sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS wordpress;
                            CREATE USER IF NOT EXISTS 'wp_user'@'localhost' IDENTIFIED BY '{{ bd_senha }}';
                            GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost';
                            FLUSH PRIVILEGES;"

    - name: Definindo permissões para o diretório do site
      command: sudo chown -R nginx:nginx /var/www/wordpress

    - name: Reiniciando Nginx
      systemd:
        name: nginx
        state: restarted
