---
- name: Configurando Nginx e PHP
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Instalando Nginx e PHP 8.2 com PHP-FPM
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - php8.2
        - php8.2-fpm

    - name: Iniciando e habilitando serviços
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - php-fpm


    - name: Criando arquivo configuração do Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/php-gilberto-lira.dreamsquad.com.br.conf
      
    - name: Criando diretório do site
      file:
        path: /var/www/html/site-exemplo
        state: directory

    - name: Copiando index.php para diretório
      copy:
        src: ./index.php
        dest: /var/www/html/site-exemplo/index.php
    
    - name: Definindo permissões para o diretório do site
      command: sudo chown -R nginx:nginx /var/www/html/site-exemplo    

    - name: Reiniciando Nginx
      systemd:
        name: nginx
        state: reloaded
       
